version: '3.8'

services:
  cosquin-rock:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run serve:ssr
    environment:
      - NODE_ENV=production